### ISSUE TITLE
Incorrect log message when login fails

### ISSUE THREAD

**Issue by exhuma** [Amazebot/bbot#114]
When using the wrong password the log messages say:

```
info:   [login] Error:User not found [403]
error:  [adapter] startup failed: User not found [403]
```

This is incorrect on two levels:

* The HTTP status code should be `401` instead of `403` (although this probably comes from the back-end?)
* The message that the user was not found is misleading.

**Comment by timkinnane** [comment]
Yeah the error message and code is just relayed from the backend. Are you connecting to a Rocket.Chat instance? Do you have a username and pass configured for a user with the bot role?

**Comment by exhuma** [comment]
Yeah. I managed to log-in. I mainly created this issue about the message itself. You can close the issue if you want as you're only relaying from the BE.
